[package]
name = "libloadorder"
version = "14.1.0"
authors = ["Oliver Hamlet <oliver@ortham.io>"]
description = "A cross-platform library for manipulating the load order and active status of plugins for the Elder Scrolls and Fallout games."
documentation = "https://docs.rs/libloadorder"
repository = "https://github.com/Ortham/libloadorder.git"
readme = "README.md"
categories = ["games", "parsing"]
license = "GPL-3.0"
edition = "2018"
exclude = [
    "target/*",
]

[badges]
coveralls = { repository = "Ortham/libloadorder" }

[dependencies]
encoding_rs = "0.8"
filetime = "0.2"
esplugin = "4.0.0"
regex = "1.0.0"
unicase = "2.0.0"
rayon = "1.0.0"

[target.'cfg(windows)'.dependencies]
app_dirs2 = "2.3"

[dev-dependencies]
criterion = "0.5.1"
tempfile = "3.0.0"

[lib]
name = "loadorder"

[workspace]
members = ["ffi"]

[[bench]]
name = "load_order"
harness = false
